In [7]:
import sys
import numpy as np
import matplotlib

np.random.seed(0)


X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]  

We're going to define is the *'two hidden'* layers.

In [3]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.randn(n_inputs, n_neurons)
    def forward(self):
        pass
    
    
print(np.random.randn(4, 3)) # Value bigger than 1, For this reason, we multiply 0.1

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]


In [4]:
print(0.1*np.random.randn(4, 3))

[[ 0.07610377  0.0121675   0.04438632]
 [ 0.03336743  0.14940791 -0.02051583]
 [ 0.03130677 -0.08540957 -0.25529898]
 [ 0.06536186  0.08644362 -0.0742165 ]]


In [9]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1* np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)
    
layer1.forward(X)
print(layer1.output)

[[-0.46060065  0.49553499  0.08326609 -0.4587313   0.34089788]
 [-1.22200575  0.36184486  0.40854986  0.73857089  1.16296097]
 [ 0.02889447 -0.05931761 -0.56936475 -0.09750155 -0.03436311]]


In [10]:
layer2.forward(layer1.output)
print(layer2.output)

[[-0.03804671  0.115508  ]
 [-0.23464641  0.2588996 ]
 [ 0.05387005  0.0024182 ]]
